export const UI_STRINGS = {
  appTitle: 'Антология текстовых квестов',
  anthologyDescription:
    'Короткие независимые интерактивные истории с локальным прогрессом.',
  prototypeTitle: 'Мобильный reader prototype',
  prototypeStatus: 'Ink runtime · локальные сохранения · reader flow',
  stories: 'Истории',
  loadingCatalog: 'Загрузка каталога…',
  catalogEmpty: 'В каталоге пока нет доступных историй.',
  catalogStart: 'Начать',
  loadingStory: 'Загрузка истории…',
  startupFailed: 'Не удалось запустить историю.',
  startStory: 'Начать историю',
  continueStory: 'Продолжить',
  viewEnding: 'Посмотреть концовку',
  menu: 'Меню',
  returnToMain: 'В главное меню',
  returnToCatalog: 'К историям',
  returnToStart: 'На стартовый экран',
  endingRestart: 'Начать сначала',
  endingMenu: 'К историям',
  exitStory: 'Выйти из истории',
  choicesLabel: 'Варианты выбора',
  readerModeLabel: 'Режим чтения',
  readerModePages: 'Страницы',
  readerModeFeed: 'Лента',
  readerModePagesHint: 'Текст автоматически заполняет доступную страницу без прокрутки.',
  readerModeFeedHint: 'Накопительная лента предыдущих фрагментов.',
  pageLabel: 'Страница',
  previousPage: 'Назад',
  nextPage: 'Вперёд',
  endingLabel: 'Концовка',
  finalTextLabel: 'Финальный текст',
  restart: 'Начать заново',
  restartConfirmation:
    'Текущий прогресс этой истории будет сброшен. Другие истории не затрагиваются.',
  cancel: 'Отмена',
  corruptedSaveReset:
    'Сохранение повреждено и было безопасно сброшено. История начата заново.',
  incompatibleSaveReset:
    'Сохранение относится к несовместимой версии истории и было сброшено.',
  storageUnavailable:
    'Локальное хранилище недоступно. История запущена без восстановления.',
  saveFailed:
    'Не удалось сохранить прогресс. Текущий сеанс продолжает работать.',
  storyActionFailed: 'Не удалось применить действие к истории.',
} as const;
