export const UI_STRINGS = {
  appTitle: 'Антология текстовых квестов',
  anthologyDescription:
    'Короткие независимые интерактивные истории с локальным прогрессом.',
  prototypeTitle: 'Мобильный reader prototype',
  prototypeStatus: 'Ink runtime · локальные сохранения · reader flow',
  stories: 'Истории',
  settings: 'Настройки',
  reading: 'Чтение',
  loadingCatalog: 'Загрузка каталога…',
  catalogEmpty: 'В каталоге пока нет доступных историй.',
  catalogStart: 'Начать',
  progressStarted: 'Прохождение начато',
  progressCompleted: 'Прохождение завершено',
  loadingStory: 'Загрузка истории…',
  startupFailed: 'Не удалось запустить историю.',
  startStory: 'Начать историю',
  continueStory: 'Продолжить',
  viewEnding: 'Посмотреть концовку',
  endings: 'Концовки',
  endingsOpened: 'Открыто концовок',
  loadingEndings: 'Загрузка концовок…',
  endingsEmptyTitle: 'Открытых концовок пока нет',
  endingsEmptyDescription:
    'Завершите прохождение истории — открытая концовка появится здесь.',
  menu: 'Меню',
  close: 'Закрыть',
  returnToMain: 'В главное меню',
  returnToCatalog: 'К историям',
  returnToStart: 'На стартовый экран',
  endingRestart: 'Начать сначала',
  endingMenu: 'К историям',
  exitStory: 'Выйти из истории',
  choicesLabel: 'Варианты выбора',
  choiceLocked: 'Недоступный вариант',
  readerModeLabel: 'Режим чтения',
  readerModePages: 'Страницы',
  readerModeFeed: 'Лента',
  readerModePagesHint: 'Текст автоматически заполняет доступную страницу без прокрутки.',
  readerModeFeedHint: 'Накопительная лента предыдущих фрагментов.',
  readerThemeLabel: 'Тема чтения',
  readerThemeHint:
    'Авто следует системной теме. Светлая, сепия, тёмная и OLED применяются только к reader.',
  pageLabel: 'Страница',
  previousPage: 'Назад',
  nextPage: 'Вперёд',
  endingLabel: 'Концовка',
  finalTextLabel: 'Финальный текст',
  restart: 'Начать заново',
  restartConfirmation:
    'Текущий прогресс этой истории будет сброшен. Уже открытые концовки и другие истории не затрагиваются.',
  cancel: 'Отмена',
  corruptedSaveReset:
    'Сохранение повреждено и было безопасно сброшено. История начата заново.',
  incompatibleSaveReset:
    'Сохранение относится к несовместимой версии истории и было сброшено.',
  storageUnavailable:
    'Локальное хранилище недоступно. Текущий экран продолжает работать без гарантии сохранения.',
  saveFailed:
    'Не удалось сохранить прогресс. Текущий сеанс продолжает работать.',
  preferenceSaveFailed:
    'Не удалось сохранить настройки чтения. Изменения действуют до перезапуска приложения.',
  endingSaveFailed:
    'Не удалось сохранить открытую концовку. Текущее прохождение не прервано.',
  storyActionFailed: 'Не удалось применить действие к истории.',
} as const;
